
reco:
	g++ -g -Wall ./src/face-recognize.cpp -o fc -I/tools/opencv-3.4.7/include/opencv4 -L/tools/opencv-3.4.7/lib -lopencv_world

performance:
	g++ -g -Wall ./src/performance.cpp -o perf -I/tools/opencv-3.4.7/include/opencv4 -L/tools/opencv-3.4.7/lib -lopencv_world